version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - weather_service
      - user_service
  weather_service:
    build: ./weather_service
    ports:
      - "5001:5001"
    environment:
      - API_KEY=your_openweather_api_key_here
  user_service:
    build: ./user_service
    ports:
      - "5002:5002"
  notification_service:
    build: ./notification_service
    ports:
      - "5003:5003"
